version: "3.8"

networks:
  mongo:
    name: mongo

volumes:
  mongo:
    name: mongo

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: leagues
      MONGO_INITDB_ROOT_PASSWORD: leagues
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: leagues
      ME_CONFIG_MONGODB_ADMINPASSWORD: leagues
      ME_CONFIG_MONGODB_URL: mongodb://leagues:leagues@leagues:27017/
    networks:
      - mongo
    ports:
      - 8081:8081
  